version: "3"

services:
  postgres:
    image: postgres:9.6.12
    container_name: MyPostgres
    restart: always
    volumes:
      - PostgresData
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=train
      - POSTGRES_USER=sean_kang
      - POSTGRES_PASSWORD=jfigames